language: csharp
mono:
  - 4.8.0
git:
  submodules: false
  depth: 1
solution: GitHub.Unity.sln
env:
   - GITHUB_UNITY_DISABLE=1
before_install:
  - wget http://beta.unity3d.com/download/d72e16ff4aba/unity-editor_amd64-5.6.3xf1Linux.deb
  - sudo dpkg -i unity-editor_amd64-5.6.3xf1Linux.deb
  - dpkg --contents unity-editor_amd64-5.5.3xf1Linux.deb
install:
  - wget http://ghfvs-installer.github.com/dependencies/deps.zip
  - unzip deps.zip -d lib/
  - ls -lisa lib/
  - mono common/nuget.exe restore
after_success:
  - rm -f unity/PackageProject/Assets/Plugins/GitHub/Editor/deleteme*
  - rm -f unity/PackageProject/Assets/Plugins/GitHub/Editor/*.pdb
  - rm -f unity/PackageProject/Assets/Plugins/GitHub/Editor/*.pdb.meta
  - rm -f unity/PackageProject/Assets/Plugins/GitHub/Editor/*.xml
  - version="`sed -En 's,.*Version = "(.*)".*,\1,p' common/SolutionInfo.cs`_$TRAVIS_COMMIT" && /opt/Unity/Editor/Unity -batchmode -projectPath "`pwd`/unity/PackageProject" -exportPackage Assets/Plugins/GitHub/Editor github-for-unity-$version.unitypackage -force-free -quit
