language: csharp
mono:
  - 4.8.0
git:
  submodules: false
  depth: 1
solution: GitHub.Unity.sln
install:
  - wget http://ghfvs-installer.github.com/dependencies/deps.zip
  - unzip deps.zip -d lib/
  - ls -lisa lib/
  - mono common/nuget.exe restore